server:
  port: 5005

spring:
  application:
    name: care-service
  datasource:
    url: ${CARE_DB_URL:jdbc:mysql://localhost:3308/care_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${CARE_DB_USERNAME:care_user}
    password: ${CARE_DB_PASSWORD:care_pass}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org.springframework.web: INFO

kafka:
  topics:
    patientAssign: ${KAFKA_TOPIC_PATIENT_ASSIGN:patient-assign}
    userRegistered: ${KAFKA_TOPIC_USER_REGISTERED:user-registered}
    auditEvents: ${KAFKA_TOPIC_AUDIT_EVENTS:audit-events}

jwt:
  issuer: "identity-service"
  audience: "your-audience"
  secret: "CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_AT_LEAST_32_CHARS"
  clockSkewSeconds: 30

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
