server:
  port: 5005

spring:
  application:
    name: care-service
  datasource:
    url: ${CARE_DB_URL:jdbc:mysql://localhost:3306/care_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${CARE_DB_USERNAME:root}
    password: ${CARE_DB_PASSWORD:mapa}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

logging:
  level:
    org.springframework.web: INFO

jwt:
  issuer: "genzipher-identity"
  audience: ""
  secret: "Ro7m3HxWZlse6kmdCNsGJXZr570I0in3NEF5Fr8UzziDJqqMn1yL7eYpXlB"
  clockSkewSeconds: 30
