server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:5173"
              - "http://localhost:5176"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
              - X-Correlation-Id
            exposedHeaders:
              - X-Correlation-Id
            allowCredentials: true

      routes:
        - id: identity-service-public
          uri: http://localhost:8050
          predicates:
            - Path=/api/auth/**

        - id: identity-service-secured
          uri: http://localhost:8050
          predicates:
            - Path=/api/users/**
          filters:
            - name: JwtAuth

        - id: care-service
          uri: http://localhost:5005
          predicates:
            - Path=/api/doctors/**,/api/patients/**,/api/assignments/**,/api/consents/**,/internal/**

gateway:
  jwt:
    issuer: "genzipher-identity"
    audience: ""
    secret: "Ro7m3HxWZlse6kmdCNsGJXZr570I0in3NEF5Fr8UzziDJqqMn1yL7eYpXlB"
    clockSkewSeconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO
